#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

sudo: required

language: generic

services:
  - docker

branches:
  except:
  - /^deploy-.*$/

env:
  global:
  - DOCKER_REPO=jlesage/baseimage-gui
  matrix:
  - DOCKERFILE=Dockerfile.alpine
    TAG=alpine-3.5
    BASEIMAGE=alpine:3.5
  - DOCKERFILE=Dockerfile.debian
    TAG=debian-stretch
    BASEIMAGE=debian:stretch-slim
  - DOCKERFILE=Dockerfile.debian
    TAG=ubuntu-16.04
    BASEIMAGE=ubuntu:16.04

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y bats

before_script:
  - travis/setenv_build_needed.sh
  - source travis/env && rm travis/env
  - test "$BUILD_NEEDED" -eq 0 || travis/before_script.sh

script:
  - test "$BUILD_NEEDED" -eq 0 || travis/script.sh

deploy:
  - provider: script
    script: travis/deploy.sh
    on:
      branch: master
      condition: "$BUILD_NEEDED = 1"
