#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

sudo: required

dist: xenial

language: generic

services:
  - docker

branches:
  except:
  - /^deploy-.*$/
  - /^.+-v[0-9.]+$/

env:
  global:
  - DOCKER_REPO=jlesage/baseimage-gui
  matrix:
  - DOCKERFILE=Dockerfile.alpine
    DOCKERTAG=alpine-3.5
    BASEIMAGE=alpine:3.5
  - DOCKERFILE=Dockerfile.alpine-glibc
    DOCKERTAG=alpine-3.5-glibc
    BASEIMAGE=alpine:3.5
  - DOCKERFILE=Dockerfile.debian
    DOCKERTAG=debian-stretch
    BASEIMAGE=debian:stretch-slim
  - DOCKERFILE=Dockerfile.debian
    DOCKERTAG=ubuntu-16.04
    BASEIMAGE=ubuntu:16.04

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y bats

before_script:
  - travis/before_script.sh

script:
  - travis/script.sh

deploy:
  - provider: script
    script: travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v.[0-9.]+$"
