#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

sudo: required

language: generic

services:
  - docker

env:
  global:
  - DOCKER_REPO=dmwilson1990/docker-baseimage-gui-cac
  matrix:
#  - DOCKER_TAG=alpine-3.12
#  - DOCKER_TAG=alpine-3.12-glibc
#  - DOCKER_TAG=alpine-3.11-glibc
#  - DOCKER_TAG=alpine-3.10
#  - DOCKER_TAG=alpine-3.10-glibc
#  - DOCKER_TAG=alpine-3.9
#  - DOCKER_TAG=alpine-3.9-glibc
#  - DOCKER_TAG=alpine-3.8
#  - DOCKER_TAG=alpine-3.7
#  - DOCKER_TAG=alpine-3.7-glibc
#  - DOCKER_TAG=alpine-3.6
#  - DOCKER_TAG=alpine-3.6-glibc
#  - DOCKER_TAG=alpine-3.5
#  - DOCKER_TAG=alpine-3.5-glibc
#  - DOCKER_TAG=debian-8
#  - DOCKER_TAG=debian-9
  - DOCKER_TAG=debian-10
#  - DOCKER_TAG=ubuntu-16.04
#  - DOCKER_TAG=ubuntu-18.04

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y bats

before_script:
  - hooks/pre_build

script:
  - |
    hooks/build && \
    env DOCKER_IMAGE="$DOCKER_REPO:$DOCKER_TAG" bats tests
