#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

sudo: required

language: generic

services:
  - docker

env:
  global:
  - DOCKER_REPO=jlesage/baseimage-gui
  - SOURCE_BRANCH=dev
  matrix:
  - DOCKER_TAG=alpine-3.6
    IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG
  - DOCKER_TAG=alpine-3.6-glibc
    IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG
  - DOCKER_TAG=alpine-3.5
    IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG
  - DOCKER_TAG=alpine-3.5-glibc
    IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG
  - DOCKER_TAG=debian-8
    IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG
  - DOCKER_TAG=ubuntu-16.04
    IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y bats

before_script:
  - hooks/pre_build

script:
  - bash -e .travis.script
